/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'erik' at '8/28/15 1:42 PM' with Gradle 2.6
 *
 * @author erik, @date 8/28/15 1:42 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
